
package cliente;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10-b140803.1500
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Ejecutar", targetNamespace = "http://Servicios/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Ejecutar {


    /**
     * 
     * @param documento
     * @param contrasena
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ejecutar", targetNamespace = "http://Servicios/", className = "cliente.Ejecutar_Type")
    @ResponseWrapper(localName = "ejecutarResponse", targetNamespace = "http://Servicios/", className = "cliente.EjecutarResponse")
    @Action(input = "http://Servicios/Ejecutar/ejecutarRequest", output = "http://Servicios/Ejecutar/ejecutarResponse")
    public String ejecutar(
        @WebParam(name = "documento", targetNamespace = "")
        String documento,
        @WebParam(name = "contrasena", targetNamespace = "")
        String contrasena);

}
