
package cliente;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10-b140803.1500
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Ejecutar", targetNamespace = "http://Servicios/", wsdlLocation = "http://localhost:8080/EjecutarBackend/Ejecutar?wsdl")
public class Ejecutar_Service
    extends Service
{

    private static URL EJECUTAR_WSDL_LOCATION;
    private final static WebServiceException EJECUTAR_EXCEPTION;
    private final static QName EJECUTAR_QNAME = new QName("http://Servicios/", "Ejecutar");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/EjecutarBackend/Ejecutar?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EJECUTAR_WSDL_LOCATION = url;
        EJECUTAR_EXCEPTION = e;
    }

    public Ejecutar_Service() {
        super(__getWsdlLocation(), EJECUTAR_QNAME);
    }

    public Ejecutar_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), EJECUTAR_QNAME, features);
    }

    public Ejecutar_Service(URL wsdlLocation) {
        super(wsdlLocation, EJECUTAR_QNAME);
    }

    public Ejecutar_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EJECUTAR_QNAME, features);
    }

    public Ejecutar_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Ejecutar_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    
    
    
    
    /**********************************************************************************************/
    private static String serviceUrl = "";

public static void setUrl(String url){
        try {
            EJECUTAR_WSDL_LOCATION = new URL(url);
        } catch (MalformedURLException ex) {
            Logger.getLogger(Ejecutar_Service.class.getName()).log(Level.SEVERE, null, ex);
        }
}
//nuevo constructor para modificar la ruta del servicio
public Ejecutar_Service(String wsdlLocation, QName serviceName) throws MalformedURLException {
    super(new URL(wsdlLocation), serviceName);
}
//
//public void ServiceClient() {
//    super(serviceUrl, new QName("http://tempuri.org/", "Service"));
//}
    /**********************************************************************************************/
    
    
    
    
    /**
     * 
     * @return
     *     returns Ejecutar
     */
    @WebEndpoint(name = "EjecutarPort")
    public Ejecutar getEjecutarPort() {
        return super.getPort(new QName("http://Servicios/", "EjecutarPort"), Ejecutar.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Ejecutar
     */
    @WebEndpoint(name = "EjecutarPort")
    public Ejecutar getEjecutarPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://Servicios/", "EjecutarPort"), Ejecutar.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EJECUTAR_EXCEPTION!= null) {
            throw EJECUTAR_EXCEPTION;
        }
        return EJECUTAR_WSDL_LOCATION;
    }

}
